settings:
  title: 'Estados de los Servicios'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo_explor-k.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los Servicios Operativos'
  notAllmonitorsOperational: 'No todos los Servicios Operando'
  monitorLabelOperational: 'En Funcionamiento'
  monitorLabelNotOperational: 'Sin Operar'
  monitorLabelNoData: 'Sin Registros'
  dayInHistogramNoData: 'Sin Registros'
  dayInHistogramOperational: 'Todo bien'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: dashboard-explork-cl
    name: Dashboard
    description: 'Dashboard de Explor-K'
    url: 'https://dashboard.explor-k.cl/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: prueba-explork-cl
    name: Prueba Reglamento
    description: 'Prueba Reglamento Angloamerican'
    url: 'https://prueba.explor-k.cl/'
    method: GET
    expectStatus: 200
    linkable: true
