settings:
  title: 'Estados de los Servicios'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo_explor-k.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los Servicios Operativos'
  notAllmonitorsOperational: 'No todos los Servicios Operando'
  monitorLabelOperational: 'En Funcionamiento'
  monitorLabelNotOperational: 'Sin Operar'
  monitorLabelNoData: 'Sin Registros'
  dayInHistogramNoData: 'Sin Registros'
  dayInHistogramOperational: 'Todo bien'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: dashboard-explork-cl
    name: Dashboard
    description: 'Dashboard de Explor-K'
    url: 'https://dashboard.explor-k.cl/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: prueba-explork-cl
    name: Prueba Reglamento
    description: 'Prueba Reglamento Angloamerican'
    url: 'https://prueba.explor-k.cl/'
    method: GET
    expectStatus: 200
    linkable: true
  
  - id: prueba2-explork-cl
    name: Prueba Inducci贸n
    description: 'Prueba Inducci贸n Angloamerican'
    url: 'https://prueba2.explor-k.cl/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: prueba-agua-explork-cl
    name: Prueba Ruta Aguas
    description: 'Prueba Ruta Aguas Angloamerican'
    url: 'https://prueba.agua.explor-k.cl/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: cursoam-explork-cl
    name: Toma de Hora AA
    description: 'Agendamiento Angloamerican'
    url: 'https://cursoam.explor-k.cl/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: reservasqm-explork-cl
    name: Toma de Hora SQM
    description: 'Agendamiento SQM'
    url: 'https://reservasqm.explor-k.cl/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: induccionsqm-explork-cl
    name: Inducci贸n SQM
    description: 'Prueba Inducci贸n SQM'
    url: 'https://induccionsqm.explor-k.cl/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: webcontrol-anglochile-cl
    name: WebControl Front
    description: 'Web WC Angloamerican'
    url: 'https://webcontrol.anglochile.cl/saac/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: wccheck-explork-cl
    name: API WebControl
    description: 'Api WebControl Explor-K'
    url: 'https://wccheck.explor-k.cl/WcCheck/'
    method: GET
    expectStatus: 200
    linkable: true